version: '3'

services:
  api:
    build: ./
    volumes:
      - './cache:/cache:rw'
      - ./.flake8:/app/.flake8:ro
      - ./app:/usr/local/lib/python3.8/site-packages/app:ro
    environment:
      - WORKERS_PER_CORE=1
      # Kobo credentials
      - KOBO_USERNAME=${KOBO_USERNAME:-kobo_user}
      - KOBO_PW
      - KOBO_ACCESS_TOKEN=${KOBO_ACCESS_TOKEN:-12345}
      - KOBO_TOKENS_FILE=${KOBO_TOKENS_FILE:./tokens/cambodia_test.json}
      # Alerts database
      - DATABASE_URL
